server:
  port: 8083

spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservice
  config:
    import: optional:configserver:http://localhost:8085