server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/chirag0101/hotel-user-ratings-microservices-configs
          clone-on-start: true